### PR TITLE
Bugfixes for NA contamination values, set pipefail and exclude RNA Extended

### PR DESCRIPTION
**Pull request by Arun-bioinformatics**
modified:   resources/home/dnanexus/process_metrics_file.py
    - Bugfixes for NA contamination values
    - Exclude RNA Extended metrics for highlighting
modified:   src/code.sh
    - include set -exo pipefail start of script

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_edit/3)

### CODE REVIEW

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_edit/3)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Arun-bioinformatics)

___
*[`resources/home/dnanexus/process_metrics_file.py` line 26 at r1](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_edit/3#-Nrk0Il83QUX-P2H1jX9:-Nrk0Il9CDXaoVT97Zzh:b-e3p9qf) ([raw file](https://github.com/eastgenomics/eggd_MetricsOutput_edit/blob/6ed1bfa995c06f6f26da76522b6e78fbd52697e0/resources/home/dnanexus/process_metrics_file.py#L26)):*
> ```Python
> from openpyxl.styles import PatternFill, Font
> from openpyxl.formatting.rule import CellIsRule
> ```

additional request could these variables be set in the main function?

**Review by Arun-bioinformatics — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_edit/3)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Aisha-D)

___
*[`resources/home/dnanexus/process_metrics_file.py` line 26 at r1](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_edit/3#-Nrk0Il83QUX-P2H1jX9:-Nrk1GOz4ysxxrkL41Px:bmfoxz1) ([raw file](https://github.com/eastgenomics/eggd_MetricsOutput_edit/blob/6ed1bfa995c06f6f26da76522b6e78fbd52697e0/resources/home/dnanexus/process_metrics_file.py#L26)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

additional request could these variables be set in the main function?
</blockquote></details>

moved into the class instead

**Review by Aisha-D — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_edit/3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arun-bioinformatics)

**Review by Aisha-D — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_edit/3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arun-bioinformatics)

**Pull request merged**
