### PR TITLE
Metrics output files

### PR DESCRIPTION
**Pull request by Arun-bioinformatics**
Created an app that converts MetricsOutput.tsv file into a MetricsOutput.xlsx file with some modifications which are normally done manually in accordance to the Helios Manual https://cuhbioinformatics.atlassian.net/wiki/spaces/O/pages/3059056641/Helios+Manual+v9.1

The PR has now been converted into an DNAnexus app

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_edit/1)

### CODE REVIEW

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/MetricsOutput_edit/1)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @Arun-bioinformatics)

___
*[`process_metrics_file.py` line 55 at r3](https://reviewable.io/reviews/eastgenomics/MetricsOutput_edit/1#-NpKNIU9C1mhkmHEI48i:-NpKNIU9C1mhkmHEI48j:bqhosei) ([raw file](https://github.com/eastgenomics/MetricsOutput_edit/blob/129b7d37e359a92ec17808126c089fe910d86dfb/process_metrics_file.py#L55)):*
> ```Python
>         self.mark_other_metrics()
>         self.wb.save(self.file)
>         print("Done!")
> ```

Can be more descriptive here, something like "xlsx file generated"
___
*[`process_metrics_file.py` line 59 at r3](https://reviewable.io/reviews/eastgenomics/MetricsOutput_edit/1#-NpKN7Lh7P7owCPSZ9fe:-NpKN7Lh7P7owCPSZ9ff:benqzzx) ([raw file](https://github.com/eastgenomics/MetricsOutput_edit/blob/129b7d37e359a92ec17808126c089fe910d86dfb/process_metrics_file.py#L59)):*
> ```Python
>     def move_rows(self) -> None:
>         """
>         Move rows in a specific way
> ```

describe the inputs + outputs of your parameters as well as the purpose of this function-  this is for all you functions btw
___
*[`process_metrics_file.py` line 67 at r3](https://reviewable.io/reviews/eastgenomics/MetricsOutput_edit/1#-NpKNa_4CaA9KGUa66yE:-NpKNa_4CaA9KGUa66yF:bwqsmhg) ([raw file](https://github.com/eastgenomics/MetricsOutput_edit/blob/129b7d37e359a92ec17808126c089fe910d86dfb/process_metrics_file.py#L67)):*
> ```Python
>     def mark_false(self) -> None:
>         """
>         Mark in red all cells with string FALSE
> ```

is this function for row 17 or the whole file?
___
*[`process_metrics_file.py` line 100 at r3](https://reviewable.io/reviews/eastgenomics/MetricsOutput_edit/1#-NpKOx6Q15q3XrC-vquF:-NpKOx6Q15q3XrC-vquG:ba1q4r5) ([raw file](https://github.com/eastgenomics/MetricsOutput_edit/blob/129b7d37e359a92ec17808126c089fe910d86dfb/process_metrics_file.py#L100)):*
> ```Python
>                         USL = self.df.loc[row][USL_column_index]
> 
>                 if value_to_compare < LSL or value_to_compare > USL:
> ```

what if value is NA due to failure to complete the pipeline? 
___
*[`process_metrics_file.py` line 152 at r3](https://reviewable.io/reviews/eastgenomics/MetricsOutput_edit/1#-NpKPn3h3xB68QAdiXsJ:-NpKPn3h3xB68QAdiXsK:b7jbaex) ([raw file](https://github.com/eastgenomics/MetricsOutput_edit/blob/129b7d37e359a92ec17808126c089fe910d86dfb/process_metrics_file.py#L152)):*
> ```Python
>                 operator = 'notBetween'
>                 formula = [LSL, USL]
>             rule = CellIsRule(operator=operator, formula=formula,
> ```

comment here plsss. Also why not incorporate the contamination highlighting here?

**Review by Arun-bioinformatics — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/MetricsOutput_edit/1)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @Aisha-D)

___
*[`process_metrics_file.py` line 55 at r3](https://reviewable.io/reviews/eastgenomics/MetricsOutput_edit/1#-NpKNIU9C1mhkmHEI48i:-NpKnloJ9S_iSy5344yi:b-3iwswk) ([raw file](https://github.com/eastgenomics/MetricsOutput_edit/blob/129b7d37e359a92ec17808126c089fe910d86dfb/process_metrics_file.py#L55)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

Can be more descriptive here, something like "xlsx file generated"
</blockquote></details>

Addressed to give a more descriptive print statement: (Done! MetricsOutput.xlsx file generated)
___
*[`process_metrics_file.py` line 59 at r3](https://reviewable.io/reviews/eastgenomics/MetricsOutput_edit/1#-NpKN7Lh7P7owCPSZ9fe:-NpKpjB-1_5dw5k16eFZ:b-896fix) ([raw file](https://github.com/eastgenomics/MetricsOutput_edit/blob/129b7d37e359a92ec17808126c089fe910d86dfb/process_metrics_file.py#L59)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

describe the inputs + outputs of your parameters as well as the purpose of this function-  this is for all you functions btw
</blockquote></details>

Done.
___
*[`process_metrics_file.py` line 67 at r3](https://reviewable.io/reviews/eastgenomics/MetricsOutput_edit/1#-NpKNa_4CaA9KGUa66yE:-NpKpt755_HbVuc3nzi6:b-7rgr5x) ([raw file](https://github.com/eastgenomics/MetricsOutput_edit/blob/129b7d37e359a92ec17808126c089fe910d86dfb/process_metrics_file.py#L67)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

is this function for row 17 or the whole file?
</blockquote></details>

This is the function for the whole file, this is because in case the format of the MetricsOutput.tsv file changed, the function would still highlight the cells which have the string "FALSE" in capital letters.
___
*[`process_metrics_file.py` line 100 at r3](https://reviewable.io/reviews/eastgenomics/MetricsOutput_edit/1#-NpKOx6Q15q3XrC-vquF:-NpKsR1y3CaympbAC8R5:bhu7gw8) ([raw file](https://github.com/eastgenomics/MetricsOutput_edit/blob/129b7d37e359a92ec17808126c089fe910d86dfb/process_metrics_file.py#L100)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

what if value is NA due to failure to complete the pipeline?
</blockquote></details>

I never thought about this to be an option, would you want me to consider it a fail if the value is equal to NA?
___
*[`process_metrics_file.py` line 152 at r3](https://reviewable.io/reviews/eastgenomics/MetricsOutput_edit/1#-NpKPn3h3xB68QAdiXsJ:-NpKsgNuDCXFpNOAuVDY:b-4ngkj9) ([raw file](https://github.com/eastgenomics/MetricsOutput_edit/blob/129b7d37e359a92ec17808126c089fe910d86dfb/process_metrics_file.py#L152)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

comment here plsss. Also why not incorporate the contamination highlighting here?
</blockquote></details>

You are right, the reason being is that this the function CellIsRule() comes from openpyxl saves me more lines of code than doing it the same way as contamination highlighting. The reason that contamination highlighting is different because there was not function that I could find from openpyxl documentation that took into account more than one condition at the time (since contamination cells are highlighted if sample values for BOTH contamination score AND contamination p value exceed)

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/MetricsOutput_edit/1)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Arun-bioinformatics)

___
*[`process_metrics_file.py` line 67 at r3](https://reviewable.io/reviews/eastgenomics/MetricsOutput_edit/1#-NpKNa_4CaA9KGUa66yE:-NpQ815r1-UvWDaFUyvf:b-bocsyo) ([raw file](https://github.com/eastgenomics/MetricsOutput_edit/blob/129b7d37e359a92ec17808126c089fe910d86dfb/process_metrics_file.py#L67)):*
<details><summary><i>Previously, Arun-bioinformatics (Arun Karnani Khemlani) wrote…</i></summary><blockquote>

This is the function for the whole file, this is because in case the format of the MetricsOutput.tsv file changed, the function would still highlight the cells which have the string "FALSE" in capital letters.
</blockquote></details>

Normally it would just be the first table. If there is FALSE elsewhere in the table that would suggest something is not right and you may want to try and catch that error but ignore it.
___
*[`process_metrics_file.py` line 100 at r3](https://reviewable.io/reviews/eastgenomics/MetricsOutput_edit/1#-NpKOx6Q15q3XrC-vquF:-NpQ0AS94BX4D-LfnaoE:bl4ipoq) ([raw file](https://github.com/eastgenomics/MetricsOutput_edit/blob/129b7d37e359a92ec17808126c089fe910d86dfb/process_metrics_file.py#L100)):*
<details><summary><i>Previously, Arun-bioinformatics (Arun Karnani Khemlani) wrote…</i></summary><blockquote>

I never thought about this to be an option, would you want me to consider it a fail if the value is equal to NA?
</blockquote></details>

No, I think if that was the case would it break the function. If its NA,then can leave as blank. Thinking of exceptions.

**Review by Arun-bioinformatics — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/MetricsOutput_edit/1)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Aisha-D)

___
*[`process_metrics_file.py` line 67 at r3](https://reviewable.io/reviews/eastgenomics/MetricsOutput_edit/1#-NpKNa_4CaA9KGUa66yE:-Nq7N7mj5PRxxusaeVhS:bt9l91p) ([raw file](https://github.com/eastgenomics/MetricsOutput_edit/blob/129b7d37e359a92ec17808126c089fe910d86dfb/process_metrics_file.py#L67)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

Normally it would just be the first table. If there is FALSE elsewhere in the table that would suggest something is not right and you may want to try and catch that error but ignore it.
</blockquote></details>

No problem, I have included a condition which raises an error if the string 'FALSE' is found in a row of the table which is not expected.
___
*[`process_metrics_file.py` line 100 at r3](https://reviewable.io/reviews/eastgenomics/MetricsOutput_edit/1#-NpKOx6Q15q3XrC-vquF:-Nq7NOTf4KMWdWpP29OI:b7zemtx) ([raw file](https://github.com/eastgenomics/MetricsOutput_edit/blob/129b7d37e359a92ec17808126c089fe910d86dfb/process_metrics_file.py#L100)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

No, I think if that was the case would it break the function. If its NA,then can leave as blank. Thinking of exceptions.
</blockquote></details>

Yes, I can confirm that cells which have an "NA" will be ignored.

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1)* status: 0 of 17 files reviewed, 10 unresolved discussions (waiting on @Arun-bioinformatics)

___
*[`dxapp.json` line 14 at r5](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1#-Nr9wIyXDZ_I3QfWFP_O:-Nr9wIyY-ziqfu342oss:blnv4h3) ([raw file](https://github.com/eastgenomics/eggd_metricsoutput_edit/blob/27b19e7e3b50e42ea07e28d9fa4f6acd0d3ab2c9/dxapp.json#L14)):*
> ```JSON
>       "optional": false,
>       "patterns": [
>         "*"
> ```

make the pattern be a tsv
___
*[`dxapp.json` line 16 at r5](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1#-Nr9wLxa7d7emivlB0m0:-Nr9wLxa7d7emivlB0m1:b-wn51m6) ([raw file](https://github.com/eastgenomics/eggd_metricsoutput_edit/blob/27b19e7e3b50e42ea07e28d9fa4f6acd0d3ab2c9/dxapp.json#L16)):*
> ```JSON
>         "*"
>       ],
>       "help": ""
> ```

add some description about file i.e where it comes from
___
*[`dxapp.json` line 40 at r5](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1#-Nr9wRLcAVP934rcT-Ug:-Nr9wRLdBJ36DOFvLsjk:b4vikgh) ([raw file](https://github.com/eastgenomics/eggd_metricsoutput_edit/blob/27b19e7e3b50e42ea07e28d9fa4f6acd0d3ab2c9/dxapp.json#L40)):*
> ```JSON
>     "timeoutPolicy": {
>       "*": {
>         "hours": 48
> ```

can this be cut down? 
___
*[`Readme.md` line 1 at r5](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1#-Nr9w__41ErfxOstdQEg:-Nr9w__41ErfxOstdQEh:bfc3yoq) ([raw file](https://github.com/eastgenomics/eggd_metricsoutput_edit/blob/27b19e7e3b50e42ea07e28d9fa4f6acd0d3ab2c9/Readme.md#L1)):*
> ```Markdown
> 
> ```

use the headers from this app https://github.com/eastgenomics/eggd_tso500 to desribe the inputs,outputs and what this app does
___
*[`Readme.developer.md` line 1 at r5](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1#-Nr9wYJt5lxht8PwbAlU:-Nr9wYJt5lxht8PwbAlV:b-3pxpoq) ([raw file](https://github.com/eastgenomics/eggd_metricsoutput_edit/blob/27b19e7e3b50e42ea07e28d9fa4f6acd0d3ab2c9/Readme.developer.md#L1)):*
> ```Markdown
> # eggd_metricsoutput_editor Developer Readme
> ```

delete this file as its not needed
___
*[`src/code.sh` line 2 at r5](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1#-Nr9x1cS45hWJ-TOIzwB:-Nr9x1cS45hWJ-TOIzwC:bqg38f3) ([raw file](https://github.com/eastgenomics/eggd_metricsoutput_edit/blob/27b19e7e3b50e42ea07e28d9fa4f6acd0d3ab2c9/src/code.sh#L2)):*
> ```Shell
> #!/bin/bash
> # eggd_metricsoutput_editor 0.0.1
> ```

delete the comments created by dnanexus. e.g from this line to main()
___
*[`src/code.sh` line 30 at r5](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1#-Nr9xC5kBraZ0qYmsNMI:-Nr9xC5kBraZ0qYmsNMJ:bss0vpt) ([raw file](https://github.com/eastgenomics/eggd_metricsoutput_edit/blob/27b19e7e3b50e42ea07e28d9fa4f6acd0d3ab2c9/src/code.sh#L30)):*
> ```Shell
>     dx download "$tsv_input" -o tsv_input
> 
>     # Fill in your application code here.
> ```

these comments seem irrelevant so delete
___
*[`src/code.sh` line 46 at r5](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1#-Nr9xKcsEDFMiBhqIN4J:-Nr9xKcsEDFMiBhqIN4K:bnazec0) ([raw file](https://github.com/eastgenomics/eggd_metricsoutput_edit/blob/27b19e7e3b50e42ea07e28d9fa4f6acd0d3ab2c9/src/code.sh#L46)):*
> ```Shell
>     sudo -H python3 -m pip install --no-index --no-deps packages/*
> 
>     if [ -z "$output_filename" ];
> ```

some description about this if statement

**Review by Arun-bioinformatics — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1)* status: 0 of 20 files reviewed, 10 unresolved discussions (waiting on @Aisha-D)

___
*[`dxapp.json` line 14 at r5](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1#-Nr9wIyXDZ_I3QfWFP_O:-NrA9AecDkHsfu8lpP5N:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_metricsoutput_edit/blob/27b19e7e3b50e42ea07e28d9fa4f6acd0d3ab2c9/dxapp.json#L14)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

make the pattern be a tsv
</blockquote></details>

Done.
___
*[`dxapp.json` line 16 at r5](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1#-Nr9wLxa7d7emivlB0m0:-NrAAiRC5G4yWP0f2gZI:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_metricsoutput_edit/blob/27b19e7e3b50e42ea07e28d9fa4f6acd0d3ab2c9/dxapp.json#L16)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

add some description about file i.e where it comes from
</blockquote></details>

Done.
___
*[`dxapp.json` line 40 at r5](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1#-Nr9wRLcAVP934rcT-Ug:-NrB0draD3fuYiYAC5Np:b-cwqnx7) ([raw file](https://github.com/eastgenomics/eggd_metricsoutput_edit/blob/27b19e7e3b50e42ea07e28d9fa4f6acd0d3ab2c9/dxapp.json#L40)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

can this be cut down?
</blockquote></details>

This has been cut down to 1 hour.
___
*[`Readme.md` line 1 at r5](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1#-Nr9w__41ErfxOstdQEg:-NrBD6Xn2V43WYXvHIq9:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_metricsoutput_edit/blob/27b19e7e3b50e42ea07e28d9fa4f6acd0d3ab2c9/Readme.md#L1)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

use the headers from this app https://github.com/eastgenomics/eggd_tso500 to desribe the inputs,outputs and what this app does
</blockquote></details>

Done.
___
*[`src/code.sh` line 2 at r5](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1#-Nr9x1cS45hWJ-TOIzwB:-NrBFX8wEr5U9nlBU9Ut:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_metricsoutput_edit/blob/27b19e7e3b50e42ea07e28d9fa4f6acd0d3ab2c9/src/code.sh#L2)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

delete the comments created by dnanexus. e.g from this line to main()
</blockquote></details>

Done.
___
*[`src/code.sh` line 30 at r5](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1#-Nr9xC5kBraZ0qYmsNMI:-NrBFXcs7KOItFvizget:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_metricsoutput_edit/blob/27b19e7e3b50e42ea07e28d9fa4f6acd0d3ab2c9/src/code.sh#L30)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

these comments seem irrelevant so delete
</blockquote></details>

Done.
___
*[`src/code.sh` line 46 at r5](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1#-Nr9xKcsEDFMiBhqIN4J:-NrBFY2r8j6Ap3T10UuM:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_metricsoutput_edit/blob/27b19e7e3b50e42ea07e28d9fa4f6acd0d3ab2c9/src/code.sh#L46)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

some description about this if statement
</blockquote></details>

Done.
___
*[`Readme.developer.md` line 1 at r5](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1#-Nr9wYJt5lxht8PwbAlU:-NrBDJ8BEZp8JnItk1f0:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_metricsoutput_edit/blob/27b19e7e3b50e42ea07e28d9fa4f6acd0d3ab2c9/Readme.developer.md#L1)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

delete this file as its not needed
</blockquote></details>

Done.

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1)* status: 0 of 20 files reviewed, 8 unresolved discussions (waiting on @Arun-bioinformatics)

___
*[`dxapp.json` line 60 at r6](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1#-NrFH6SuAs1QdnGMz9LQ:-NrFH6SuAs1QdnGMz9LR:b414a9k) ([raw file](https://github.com/eastgenomics/eggd_metricsoutput_edit/blob/43b6845756954f755624b898516182c8f06db9fd/dxapp.json#L60)):*
> ```JSON
>       "systemRequirements": {
>         "*": {
>           "instanceType": "mem1_ssd1_v2_x4"
> ```

can this be dropped to the instance mem1_ssd1_v2_x2 ? Dont think it needs much mem or cpu for the amount of work the app is using? its half the cost
___
*[`Readme.md` line 15 at r6](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1#-NrFHVLP4_tV_L4LWa4k:-NrFHVLP4_tV_L4LWa4l:bt2dvc3) ([raw file](https://github.com/eastgenomics/eggd_metricsoutput_edit/blob/43b6845756954f755624b898516182c8f06db9fd/Readme.md#L15)):*
> ```Markdown
> 
> ## How does this app work?
> The app runs a python script to create an .xlsx file from the provided .tsv file and modifies the .xlsx file in accordance to the [Helios Manual v10][helios-manual]. The general outline is as follows:
> ```

can you link to page "Live cancer guide" cause if the manual gets updated, this link will break. Can perhaps say in accordance to the quality control checks in the Helios manual. Then link to  that parent page live cancer guide
___
*[`Readme.md` line 20 at r6](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1#-NrFHqGkER9-gT5LegY-:-NrFHqGkER9-gT5LegY0:b-3nrvve) ([raw file](https://github.com/eastgenomics/eggd_metricsoutput_edit/blob/43b6845756954f755624b898516182c8f06db9fd/Readme.md#L20)):*
> ```Markdown
> - create an .xlsx file from the .tsv file
> - make the following modifications on the first .xlsx worksheet called "MetricsOutput"
>     -  move all cells of rows 16 to 19 and from column B 2 cells to the right. alt text
> ```

Rename the sample names with columns sample1, sample2 like you have with the other screenshot, its a good thing to reduce sharing sample names, even though they are annonymised.
___
*[`resources/home/dnanexus/process_metrics_file.py` line 240 at r6](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1#-NrFJ3b5AmbJ7dc9mOsI:-NrFJ3b5AmbJ7dc9mOsJ:b-tkdi49) ([raw file](https://github.com/eastgenomics/eggd_metricsoutput_edit/blob/43b6845756954f755624b898516182c8f06db9fd/resources/home/dnanexus/process_metrics_file.py#L240)):*
> ```Python
>             converted_row = []
>             for item in row:
>                 try:
> ```

why are you converting to a float or int. And if it fits neither, an error is not raised

**Review by woook — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1)* status: 0 of 20 files reviewed, 9 unresolved discussions (waiting on @Aisha-D and @Arun-bioinformatics)

___
*[`Readme.md` line 29 at r6](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1#-NrG9AeS1F5lhBAkyYld:-NrG9AeS1F5lhBAkyYle:b-srhc8s) ([raw file](https://github.com/eastgenomics/eggd_metricsoutput_edit/blob/43b6845756954f755624b898516182c8f06db9fd/Readme.md#L29)):*
> ```Markdown
> Returns a .xlsx file with all the requested changes. As an example, the figures below depicts how the excel file looks before and after any modifications implemented.
> 
> - MetricsOutput file after any modifications:alt text
> ```

before



_Code quote:_
```Markdown
after
```

**Review by Arun-bioinformatics — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1)* status: 0 of 20 files reviewed, 9 unresolved discussions (waiting on @Aisha-D and @woook)

___
*[`dxapp.json` line 60 at r6](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1#-NrFH6SuAs1QdnGMz9LQ:-NrG-wlPC45le9VZquHO:b-o7z7hi) ([raw file](https://github.com/eastgenomics/eggd_metricsoutput_edit/blob/43b6845756954f755624b898516182c8f06db9fd/dxapp.json#L60)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

can this be dropped to the instance mem1_ssd1_v2_x2 ? Dont think it needs much mem or cpu for the amount of work the app is using? its half the cost
</blockquote></details>

Will work with mem1_ssd1_v2_x2
___
*[`Readme.md` line 15 at r6](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1#-NrFHVLP4_tV_L4LWa4k:-NrG29zG5O4-xFNd8zpU:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_metricsoutput_edit/blob/43b6845756954f755624b898516182c8f06db9fd/Readme.md#L15)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

can you link to page "Live cancer guide" cause if the manual gets updated, this link will break. Can perhaps say in accordance to the quality control checks in the Helios manual. Then link to  that parent page live cancer guide
</blockquote></details>

Done.
___
*[`Readme.md` line 20 at r6](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1#-NrFHqGkER9-gT5LegY-:-NrG1uAI55cS064H1PLl:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_metricsoutput_edit/blob/43b6845756954f755624b898516182c8f06db9fd/Readme.md#L20)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

Rename the sample names with columns sample1, sample2 like you have with the other screenshot, its a good thing to reduce sharing sample names, even though they are annonymised.
</blockquote></details>

Done.
___
*[`Readme.md` line 29 at r6](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1#-NrG9AeS1F5lhBAkyYld:-NrGCXLa1358zZwXrUVX:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_metricsoutput_edit/blob/43b6845756954f755624b898516182c8f06db9fd/Readme.md#L29)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

before
</blockquote></details>

Done.

**Review by Arun-bioinformatics — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1)* status: 0 of 20 files reviewed, 9 unresolved discussions (waiting on @Aisha-D and @woook)

___
*[`resources/home/dnanexus/process_metrics_file.py` line 240 at r6](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1#-NrFJ3b5AmbJ7dc9mOsI:-NrGbIwXC31p_8vp5eXG:btutwgq) ([raw file](https://github.com/eastgenomics/eggd_metricsoutput_edit/blob/43b6845756954f755624b898516182c8f06db9fd/resources/home/dnanexus/process_metrics_file.py#L240)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

why are you converting to a float or int. And if it fits neither, an error is not raised
</blockquote></details>

Discussed in a huddle

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1)* status: 0 of 20 files reviewed, 3 unresolved discussions (waiting on @Arun-bioinformatics and @woook)

___
*[`Readme.md` line 15 at r6](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1#-NrFHVLP4_tV_L4LWa4k:-NrGjdY6DAiUmREzK-4-:b-5elgoy) ([raw file](https://github.com/eastgenomics/eggd_metricsoutput_edit/blob/43b6845756954f755624b898516182c8f06db9fd/Readme.md#L15)):*
<details><summary><i>Previously, Arun-bioinformatics (Arun Karnani Khemlani) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

remove v10

**Review by Arun-bioinformatics — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1)* status: 0 of 20 files reviewed, 2 unresolved discussions (waiting on @Aisha-D and @woook)

___
*[`Readme.md` line 15 at r6](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1#-NrFHVLP4_tV_L4LWa4k:-NrGkJA2CnToGy2CMVwW:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_metricsoutput_edit/blob/43b6845756954f755624b898516182c8f06db9fd/Readme.md#L15)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

remove v10
</blockquote></details>

Done.

**Review by Aisha-D — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 10 of 15 files at r5, 4 of 7 files at r6, 3 of 4 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1)* status: all files reviewed, 1 unresolved discussion (waiting on @woook)

**Review by Aisha-D — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_metricsoutput_edit/1)* status: all files reviewed, 1 unresolved discussion (waiting on @woook)

**Pull request merged**
