### PR TITLE
Bugfix eggd_metrics_output editor, update to v1.1.0?

### PR DESCRIPTION
**Pull request by Arun-bioinformatics**
modified:   dxapp.json
- Update from v1.0.0 to v1.1.0

modified:   resources/home/dnanexus/process_metrics_file.py
- Update mark_other_metrics() method to make highlighting cells colouring work in LibreOffice and Excel

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_editor/5)

### CODE REVIEW

**Comment by Jay-Miles** [comment]
*[`resources/home/dnanexus/process_metrics_file.py` line 46 at r1](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_editor/5#-Nv1rTN08wT_4uCWrFfE:-Nv1rTN08wT_4uCWrFfF:b-ehdso4) ([raw file](https://github.com/eastgenomics/eggd_MetricsOutput_editor/blob/c93541559f8d8245b9ec4021a0dcda06ad8f21ea/resources/home/dnanexus/process_metrics_file.py#L46)):*
> ```Python
>         Parameters
>         ----------
>         ws : openpyxl.worksheet.worksheet.Worksheet
> ```

ws isn't an argument in the function definition - should it be?
If not, it doesn't need to be in the list of arguments.

**Comment by Jay-Miles** [comment]
*[`resources/home/dnanexus/process_metrics_file.py` line 107 at r1](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_editor/5#-Nv1sxRV0xyYKLpP7VmD:-Nv1sxRV0xyYKLpP7VmE:bc8zeym) ([raw file](https://github.com/eastgenomics/eggd_MetricsOutput_editor/blob/c93541559f8d8245b9ec4021a0dcda06ad8f21ea/resources/home/dnanexus/process_metrics_file.py#L107)):*
> ```Python
> 
>         """
>         string_to_find = "FALSE"
> ```

This variable is only used once, would it be simpler to just replace the only instance of this variable with the string itself?

**Review by Arun-bioinformatics — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_editor/5)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Jay-Miles)

___
*[`resources/home/dnanexus/process_metrics_file.py` line 46 at r1](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_editor/5#-Nv1rTN08wT_4uCWrFfE:-Nv1zozpBOgS5IR3V9jD:b-s8hxmm) ([raw file](https://github.com/eastgenomics/eggd_MetricsOutput_editor/blob/c93541559f8d8245b9ec4021a0dcda06ad8f21ea/resources/home/dnanexus/process_metrics_file.py#L46)):*
<details><summary><i>Previously, Jay-Miles wrote…</i></summary><blockquote>

ws isn't an argument in the function definition - should it be?
If not, it doesn't need to be in the list of arguments.
</blockquote></details>

No it isn't, sorry I had to change the function a couple of times and I forgot to update the docstring
___
*[`resources/home/dnanexus/process_metrics_file.py` line 107 at r1](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_editor/5#-Nv1sxRV0xyYKLpP7VmD:-Nv2-6vQ4Bl9QVKX8MCv:biezqoj) ([raw file](https://github.com/eastgenomics/eggd_MetricsOutput_editor/blob/c93541559f8d8245b9ec4021a0dcda06ad8f21ea/resources/home/dnanexus/process_metrics_file.py#L107)):*
<details><summary><i>Previously, Jay-Miles wrote…</i></summary><blockquote>

This variable is only used once, would it be simpler to just replace the only instance of this variable with the string itself?
</blockquote></details>

You are right, I have amended this

**Review by Jay-Miles — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_editor/5)* status: 1 of 2 files reviewed, all discussions resolved

**Review by Jay-Miles — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_editor/5#-:-Nv21TwL0za5jntxznTX:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved

**Review by Jay-Miles — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_MetricsOutput_editor/5)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arun-bioinformatics)

**Pull request merged**
